/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  introductionSidebar: [
    'intro',
    'alltopic',
  ],
  RLsidebar: [
    {
      type: 'category',
      label: 'Reinforcement Learning',
      items: [
        'ReinforcementLearning/Introduction/intro',
      ],
    },
    {
      type: 'category',
      label: 'Markov Decision Process',
      items: [
        'ReinforcementLearning/MarkovDecisionProcesses/index',
      ],
    },
    {
      type: 'category',
      label: 'Dynamic Programming',
      items: [
        'ReinforcementLearning/DynamicProgramming/index',
      ],
    },
    {
      type: 'category',
      label: 'Monte Carlo Methods',
      items: [
        'ReinforcementLearning/MonteCarlos/index',
      ],
    },
    {
      type: 'category',
      label: 'Deep RL',
      items: [
        'ReinforcementLearning/DeepRL/index',
      ],
    },
    {
      type: 'category',
      label: 'On-Policy Prediction with Approximation',
      items: [
        'ReinforcementLearning/OffOnPolicy/index',
      ],
    },
    {
      type: 'category',
      label: 'Applications of Reinforcement Learning',
      items: [
        'ReinforcementLearning/Applications/index',
      ],
    }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
